/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FacultyImport } from './routes/faculty'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ApplyIndexImport } from './routes/apply/index'
import { Route as ApplyApplyStartImport } from './routes/apply/apply.start'

// Create/Update Routes

const FacultyRoute = FacultyImport.update({
  path: '/faculty',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ApplyIndexRoute = ApplyIndexImport.update({
  path: '/apply/',
  getParentRoute: () => rootRoute,
} as any)

const ApplyApplyStartRoute = ApplyApplyStartImport.update({
  path: '/apply/apply/start',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyImport
      parentRoute: typeof rootRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyIndexImport
      parentRoute: typeof rootRoute
    }
    '/apply/apply/start': {
      id: '/apply/apply/start'
      path: '/apply/apply/start'
      fullPath: '/apply/apply/start'
      preLoaderRoute: typeof ApplyApplyStartImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/apply': typeof ApplyIndexRoute
  '/apply/apply/start': typeof ApplyApplyStartRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/apply': typeof ApplyIndexRoute
  '/apply/apply/start': typeof ApplyApplyStartRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/apply/': typeof ApplyIndexRoute
  '/apply/apply/start': typeof ApplyApplyStartRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faculty'
    | '/apply'
    | '/apply/apply/start'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/faculty' | '/apply' | '/apply/apply/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faculty'
    | '/apply/'
    | '/apply/apply/start'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FacultyRoute: typeof FacultyRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
  ApplyApplyStartRoute: typeof ApplyApplyStartRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FacultyRoute: FacultyRoute,
  ApplyIndexRoute: ApplyIndexRoute,
  ApplyApplyStartRoute: ApplyApplyStartRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/faculty",
        "/apply/",
        "/apply/apply/start"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/faculty": {
      "filePath": "faculty.tsx"
    },
    "/apply/": {
      "filePath": "apply/index.tsx"
    },
    "/apply/apply/start": {
      "filePath": "apply/apply.start.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
